### ISSUE TITLE
MultiSourceTable 

### ISSUE THREAD

**Issue by hmahdavi921** [keithcstone/Crewstone_DNN_7.0#1]
> Error: CodeSmith.Engine.CodeTemplateValidationException: Template is not valid. The 'Module.css.cst' template property 'MultiSourceTable' is required and was not set in the master 'DnnMaster.cst' template.
>    at CodeSmith.Engine.CodeTemplate.Render(TextWriter writer)
>    at CodeSmith.Engine.CodeTemplate.RenderToString()
>    at CodeSmith.Engine.CodeTemplate.RenderToFile(OutputFile outputFile, Boolean overwrite)
>    at CodeSmith.Engine.CodeTemplate.RenderToFile(String path, Boolean overwrite)
>    at _CodeSmith.DnnMaster_cst.RunTemplates(TableSchemaCollection MultiSourceTable, String ModuleName) in g:\program\CodeSmith Professional 7.0\Crewstone_DNN_7.0-master\DnnMaster.cst:line 1219

*_I set MultiSourceTable but get this error .Please advice_

**Comment by keithcstone** [comment]
It sounds like you're not executing the correct template. Please give more details since I cannot determine the issue without knowing how to reproduce the problem.

**Comment by hmahdavi921** [comment]
I post all options for you in this case  .
[image: تصویر درون برنامه‌ای 3][image: تصویر درون برنامه‌ای 2].[image:
تصویر درون برنامه‌ای 1]

2016-02-01 17:05 GMT+03:30 Keith Stone notifications@github.com:

> It sounds like you're not executing the correct template. Please give more
> details since I cannot determine the issue without knowing how to reproduce
> the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/keithcstone/Crewstone_DNN_7.0/issues/1#issuecomment-177974813
> .

## 

موفق و پیروز باشید.

**Comment by keithcstone** [comment]
Sorry, but none of the images are showing.

**Comment by hmahdavi921** [comment]
Sorry , Now you can see images.

2016-02-01 19:09 GMT+03:30 Keith Stone notifications@github.com:

> Sorry, but none of the images are showing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/keithcstone/Crewstone_DNN_7.0/issues/1#issuecomment-178029640
> .

## 

موفق و پیروز باشید.

**Comment by keithcstone** [comment]
No, all I see is [image: تصویر درون برنامه‌ای 2].

**Comment by hmahdavi921** [comment]
I attach the  all images. Please see files

2016-02-01 20:04 GMT+03:30 Keith Stone notifications@github.com:

> No, all I see is [image: تصویر درون برنامه‌ای 2].
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/keithcstone/Crewstone_DNN_7.0/issues/1#issuecomment-178058730
> .

## 

موفق و پیروز باشید.

**Comment by keithcstone** [comment]
I never could see the images, but it looks like the wrong version of module.css.cst was pushed, so I fixed that and of you pull the updated template you're good. Essentially it's removing unused references in module.css.cst, since that template simply creates the empty css file in the correct location.
